# Generated by Django 3.1.6 on 2021-03-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_child',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
