# Generated by Django 3.1.6 on 2021-03-02 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210302_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='child_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='store.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='store.category'),
        ),
    ]
