# Generated by Django 3.1.6 on 2021-03-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210302_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='child_category',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
