# Generated by Django 3.1.6 on 2021-03-02 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210302_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, editable=models.BooleanField(default=True), null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
