# Generated by Django 3.1.6 on 2021-03-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
    ]
