# Generated by Django 3.1.6 on 2021-05-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210505_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_published',
            field=models.IntegerField(default=1900),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=50),
        ),
    ]
