# Generated by Django 3.1.6 on 2021-05-05 20:51

from django.db import migrations

from store.models import Category, Author, Book


def populate_database(apps, schema_editor):
    Category.objects.all().delete()
    Author.objects.all().delete()

    # Categories
    parent1 = Category.objects.create(name='Fiction', is_child=False, parent_category=None)
    category1 = Category.objects.create(name='Science & Fiction', is_child=True, parent_category=parent1)
    category2 = Category.objects.create(name='Action & adventure', is_child=True, parent_category=parent1)
    category3 = Category.objects.create(name='Historical Fiction', is_child=True, parent_category=parent1)
    category4 = Category.objects.create(name='Poetry', is_child=True, parent_category=parent1)
    category5 = Category.objects.create(name='Fantasy', is_child=True, parent_category=parent1)
    category6 = Category.objects.create(name='Horror', is_child=True, parent_category=parent1)
    category7 = Category.objects.create(name='Thriller', is_child=True, parent_category=parent1)
    category8 = Category.objects.create(name='Westerns', is_child=True, parent_category=parent1)
    category9 = Category.objects.create(name='Graphic Novels & Comics', is_child=True, parent_category=parent1)
    category10 = Category.objects.create(name='Romance', is_child=True, parent_category=parent1)
    category11 = Category.objects.create(name='Mystery & Crime', is_child=True, parent_category=parent1)
    category25 = Category.objects.create(name='War', is_child=True, parent_category=parent1)
    category26 = Category.objects.create(name='Manga', is_child=True, parent_category=parent1)

    parent2 = Category.objects.create(name='Nonfiction', is_child=False, parent_category=None)
    category12 = Category.objects.create(name='Art/architecture & Photography', is_child=True, parent_category=parent2)
    category13 = Category.objects.create(name='Biography', is_child=True, parent_category=parent2)
    category14 = Category.objects.create(name='Cookbook', is_child=True, parent_category=parent2)
    category15 = Category.objects.create(name='Home & Garden', is_child=True, parent_category=parent2)
    category16 = Category.objects.create(name='Education', is_child=True, parent_category=parent2)
    category17 = Category.objects.create(name='Business', is_child=True, parent_category=parent2)
    category18 = Category.objects.create(name='Health/fitness', is_child=True, parent_category=parent2)
    category19 = Category.objects.create(name='Engineering', is_child=True, parent_category=parent2)
    category20 = Category.objects.create(name='Humor', is_child=True, parent_category=parent2)
    category21 = Category.objects.create(name='Nature', is_child=True, parent_category=parent2)
    category22 = Category.objects.create(name='Travel', is_child=True, parent_category=parent2)
    category23 = Category.objects.create(name='Philosophy', is_child=True, parent_category=parent2)
    category24 = Category.objects.create(name='Science & Technology', is_child=True, parent_category=parent2)

    # Authors
    author1 = Author.objects.create(name='George R.R.', surname='Martin')
    author2 = Author.objects.create(name='C.S.', surname='Lewis')
    author3 = Author.objects.create(name='Jack', surname='Higgins')
    author4 = Author.objects.create(name='Dan', surname='Brown')
    author5 = Author.objects.create(name='Louise', surname='Hay')
    author6 = Author.objects.create(name='Agatha', surname='Christie')
    author7 = Author.objects.create(name='Stephen', surname='Hawking')
    author8 = Author.objects.create(name='Robert T.', surname='Kiyosaki')
    author9 = Author.objects.create(name='James', surname='Rollins')
    author10 = Author.objects.create(name='Minka', surname='Kent')
    author11 = Author.objects.create(name='Darcy', surname='Coates')
    author12 = Author.objects.create(name='Dean', surname='Koontz')
    author13 = Author.objects.create(name='Diana', surname='Gabaldon')
    author14 = Author.objects.create(name='Sarah', surname='J. Maas')
    author15 = Author.objects.create(name='Margaret', surname='Atwood')
    author16 = Author.objects.create(name='V. E.', surname='Schwab')
    author17 = Author.objects.create(name='David ', surname='Baldacci')
    author18 = Author.objects.create(name='J.K.', surname='Rowling')
    author19 = Author.objects.create(name='Lee', surname='Child')
    author20 = Author.objects.create(name='Rosella', surname='Postorino')
    author21 = Author.objects.create(name='Anita', surname='Abriel')
    author22 = Author.objects.create(name='Marie', surname='Benedict')
    author23 = Author.objects.create(name='Serena', surname='Burdick')
    author24 = Author.objects.create(name='Sharon', surname='Kay Penman')
    author25 = Author.objects.create(name='Courtney', surname='Peppernell')
    author26 = Author.objects.create(name='Morgan', surname='Harper Nichols')
    author27 = Author.objects.create(name='Mary', surname='Oliver')
    author28 = Author.objects.create(name='Timothy', surname='Zahn')
    author29 = Author.objects.create(name='Stephen', surname='Graham Jones')
    author30 = Author.objects.create(name='Brian', surname='Panowich')
    author31 = Author.objects.create(name=' William', surname='W. Johnstone')
    author32 = Author.objects.create(name='Anna', surname='North')
    author33 = Author.objects.create(name='Gregory', surname='A. Freeman')
    author34 = Author.objects.create(name='Adam', surname='Makos')
    author35 = Author.objects.create(name='Masashi', surname='Kishimoto')
    author36 = Author.objects.create(name='Tite', surname='Kubo')
    author37 = Author.objects.create(name='Hajime ', surname='Isayama')
    author38 = Author.objects.create(name='Colleen', surname='Hoover')
    author39 = Author.objects.create(name='Christine', surname='Feehan')
    author40 = Author.objects.create(name='Robert', surname='Macfarlane')
    author41 = Author.objects.create(name='Erik', surname='Larson')
    author42 = Author.objects.create(name='Billie', surname='Ellish')
    author43 = Author.objects.create(name='Ta-Nehisi ', surname='Coates')
    author44 = Author.objects.create(name='Barack', surname='Obama')
    author45 = Author.objects.create(name='Rob', surname='Kenner')
    author46 = Author.objects.create(name='Bill', surname='Cowher')
    author47 = Author.objects.create(name='Harley', surname='Pasternak')
    author48 = Author.objects.create(name='Heidi', surname='Swanson')
    author49 = Author.objects.create(name='Nigella', surname='Lawson')
    author50 = Author.objects.create(name='Molly', surname='Baz')
    author51 = Author.objects.create(name='Taku', surname='Furuya')
    author52 = Author.objects.create(name='Clea', surname='Shearer')
    author53 = Author.objects.create(name='Erin', surname='Benzakein')
    author54 = Author.objects.create(name='Josh', surname='Hawley')


    # Books
    # Fiction
    book1 = Book.objects.create(author=author1,
                                title='A Game of Thrones',
                                price='60',
                                first_published=2003,
                                description='This first book in the A Song of Ice and Fire series boasts intricate plots, characters threatened with death, and a world chock-full of wizards, knights, ladies, and bastards. The book follows three storylines: one set in the seven kingdoms, another on the wall, and the third across the sea.',
                                url='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwritingcenter.mcdaniel.edu%2Fwp-content%2Fuploads%2F2012%2F11%2Fa-game-of-thrones-book-1-of-a-song-of-ice-and-fire.jpg&f=1&nofb=1')
    book1.category.set([parent1, category5])

    book2 = Book.objects.create(author=author2,
                                title='The Lion the Witch and The Wardrobe',
                                price='30',
                                first_published=1960,
                                description='Master storyteller C.S. Lewis introduces us to the magical world of Narnia as Lucy, Edmund, Peter, and Susan enter it through a wardrobe in their uncle’s house. Edmund encounters the White Witch, who convinces him to betray his siblings, but the Great Lion Aslan comes to their rescue—and that of the whole world of Narnia.',
                                url='https://duckduckgo.com/i/70cc686b.jpg')
    book2.category.set([parent1, category5])

    book3 = Book.objects.create(author=author3,
                                title='The Eagle Has Landed',
                                price='33.99',
                                first_published=2010,
                                description='Meanwhile, in a quiet seaside village, a beautiful widow and an IRA assassin have already laid the groundwork for what will be the most treacherous plot of the war. It begins on November 6, 1943, when Berlin receivs the fateful message...',
                                url='https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/TheEagleHasLanded.jpg/220px-TheEagleHasLanded.jpg')
    book3.category.set([parent1, category25, category7])

    book4 = Book.objects.create(author=author4,
                                title='The Da Vinci Code',
                                price='61.99',
                                first_published=2018,
                                description='While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter. Even more startling, the late curator was involved in the Priory of Sion—a secret society whose members included Sir Isaac Newton, Victor Hugo, and Da Vinci—and he guarded a breathtaking historical secret. Unless Langdon and Neveu can decipher the labyrinthine puzzle—while avoiding the faceless adversary who shadows their every move—the explosive, ancient truth will be lost forever.',
                                url='https://images-na.ssl-images-amazon.com/images/I/41KuPr7kpZL._SX277_BO1,204,203,200_.jpg')
    book4.category.set([parent1, category11, category7])
    # Non-fiction
    book5 = Book.objects.create(author=author54,
                                title='The Tyranny of Big Tech',
                                price='26.99',
                                first_published=2021,
                                description='Big Tech and its allies do not deal gently with those who cross them, and Senator Hawley proudly bears his own battle scars. But hubris is dangerous. The time is ripe to overcome the tyranny of Big Tech by reshaping the business and legal landscape of the digital world.',
                                url='https://prodimage.images-bn.com/pimages/9781684512393_p0_v4_s550x406.jpg')
    book5.category.set([parent2, category19])
    # Fiction
    book6 = Book.objects.create(author=author6,
                                title='And Then There Were None',
                                price='41.39',
                                first_published=1939,
                                description='Ten . . . Ten strangers are lured to an isolated island mansion off the Devon coast by a mysterious "U. N. Owen. Nine . . . At dinner a recorded message accuses each of them in turn of having a guilty secret, and by the end of the night one of the guests is dead. Eight . . . Stranded by a violent storm, and haunted by a nursery rhyme counting down one by one . . . as one by one . . . they begin to die. Seven . . .Which among them is the killer and will any of them survive?',
                                url='https://upload.wikimedia.org/wikipedia/en/4/4a/And_Then_There_Were_None_First_Edition_Cover_1939.jpg')
    book6.category.set([parent1, category11])

    # Non-fiction
    book7 = Book.objects.create(author=author7,
                                title='A Brief History of Time',
                                price='51.99',
                                first_published=1988,
                                description='A landmark volume in science writing by one of the great minds of our time, Stephen Hawking’s book explores such profound questions as: How did the universe begin—and what made its start possible? Does time always flow forward? Is the universe unending—or are there boundaries? Are there other dimensions in space? What will happen when it all ends? Told in language we all can understand, A Brief History of Time plunges into the exotic realms of black holes and quarks, of antimatter and “arrows of time,” of the big bang and a bigger God—where the possibilities are wondrous and unexpected. With exciting images and profound imagination, Stephen Hawking brings us closer to the ultimate secrets at the very heart of creation.',
                                url='https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/BriefHistoryTime.jpg/220px-BriefHistoryTime.jpg')
    book7.category.set([parent2, category24])

    book8 = Book.objects.create(author=author8,
                                title='Rich Dad Poor Dad',
                                price='31.99',
                                first_published=2017,
                                description='The #1 Personal Finance book of all time, Robert Kiyosaki shares the story of his two dad: his real father, whom he calls his poor dad, \' and the father of his best friend, the man who became his mentor and his rich dad.\' One man was well educated and an employee all his life, the other\'s education was street smarts" over traditional classroom education and he took the path of entrepreneurship a road that led him to become one of the wealthiest men in Hawaii. Robert\'s poor dad struggled financially all his life, and these two dads?these very different points of view of money, investing, and employment shaped Robert\'s thinking about money.',
                                url='https://images-na.ssl-images-amazon.com/images/I/51fbpKt3-JL._SX331_BO1,204,203,200_.jpg')
    book8.category.set([parent2, category17])

    #  Fiction
    book9 = Book.objects.create(author=author9,
                                title='Sandstorm',
                                price='9.99',
                                first_published=2004,
                                description='Twenty years ago, a wealthy British financier disappeared near Ubar, the fabled lost city buried beneath the sands of Oman. Now, an expedition of scientists, led by the financier’s daughter, is finally setting off for the legendary metropolist to unlock the desert’s secrets. What they find, however, is more beautiful than they ever dreamed—and far deadlier. Within Ubar is a powerful energy source that could fuel the entire earth above—if it can be harnessed. ',
                                url='https://prodimage.images-bn.com/pimages/9780062017581_p0_v2_s550x406.jpg')
    book9.category.set([parent1, category2])

    book10 = Book.objects.create(author=author10,
                                title='The Watcher Girl',
                                price='19.99',
                                first_published=2007,
                                description='A woman’s suspicions about her ex-boyfriend become a dangerous obsession in a twisting novel of psychological suspense by Washington Post and Wall Street Journal bestselling author Minka Kent.',
                                url='https://images-na.ssl-images-amazon.com/images/I/81ZywiVlouL.SR160,240_BG243,243,243.jpg')
    book10.category.set([parent1, category7])

    book11 = Book.objects.create(author=author10,
                                 title='When I Was You ',
                                 price='15.99',
                                 first_published=2004,
                                 description='A stolen identity leads a woman down a dark and desperate path in a gripping novel of psychological suspense by Wall Street Journal bestselling author Minka Kent. After barely surviving a brutal attack, Brienne Dougray rarely leaves her house. Suffering from debilitating headaches and memory loss, she can rely only on her compassionate new tenant, Dr. Niall Emberlin, a welcome distraction from the discomfiting bubble that has become her existence.',
                                 url='https://m.media-amazon.com/images/I/41TyAL9OHGL._SY346_.jpg')
    book11.category.set([parent1, category7])

    book12 = Book.objects.create(author=author11,
                                 title='The Whispering Dead',
                                 price='25.99',
                                 first_published=2021,
                                 description='The cemetery is alive with faint, spectral shapes, led by a woman who died before her time...and Keira, the only person who can see her, has become her new target. Determined to help put the ghost to rest, Keira digs into the spirit is past life with the help of unlikely new friends, and discovers a history of deception, ill-fated love, and murder.',
                                 url='https://prodimage.images-bn.com/pimages/9781728239217_p0_v2_s550x406.jpg')
    book12.category.set([parent1, category6])

    book13 = Book.objects.create(author=author12,
                                 title='Deeply Odd',
                                 price='19.99',
                                 first_published=2014,
                                 description='The pistol appeared in his hand the way a dove appears in the hand of a good magician, as if it materialized out of thin air. “You think I won’t do it right here in the open. But you’d be surprised. . . . You’ll drop before you get the breath to scream.”  ',
                                 url='https://prodimage.images-bn.com/pimages/9780553593082_p0_v1_s550x406.jpg')
    book13.category.set([parent1, category6])

    book14 = Book.objects.create(author=author12,
                                 title='Odd Thomas',
                                 price='19.99',
                                 first_published=2012,
                                 description='A stranger comes to Pico Mundo, accompanied by a horde of hyena-like shades who herald an imminent catastrophe. Aided by his soul mate, Stormy Llewellyn, and an unlikely community of allies that includes the King of Rock ’n’ Roll, Odd will race against time to thwart the gathering evil. His account of these shattering hours, in which past and present, fate and destiny, converge, is a testament by which to live—an unforgettable fable for our time destined to rank among Dean Koontz’s most enduring works.',
                                 url='https://prodimage.images-bn.com/pimages/9780345533425_p0_v1_s550x406.jpg')
    book14.category.set([parent1, category6])

    book15 = Book.objects.create(author=author13,
                                 title='Go Tell the Bees That I Am Gone',
                                 price='29.99',
                                 first_published=2021,
                                 description='The past may seem the safest place to be .. but it is the most dangerous time to be alive...Jamie Fraser and Claire Randall were torn apart by the Jacobite Rising in 1746, and it took them twenty years to find each other again. Now the American Revolution threatens to do the same.',
                                 url='https://prodimage.images-bn.com/pimages/9781101885680_p0_v2_s550x406.jpg')
    book15.category.set([parent1, category1])

    book16 = Book.objects.create(author=author14,
                                 title='A Court of Silver Flames',
                                 price='20.99',
                                 first_published=2021,
                                 description='After years following the epic journey of Feyre, her sister Nesta finally takes center stage in this highly anticipated tale all her own. Now that the war has finally ended, the mesmerizing A Court of Thorns and Roses saga continues, and fiery Nesta is ready to embrace her fight and fate.',
                                 url='https://prodimage.images-bn.com/pimages/9781681196282_p0_v6_s550x406.jpg')
    book16.category.set([parent1, category1])

    book17 = Book.objects.create(author=author15,
                                 title='The Handmaid\'s Tale',
                                 price='20.99',
                                 first_published=1998,
                                 description='An instant classic and eerily prescient cultural phenomenon, from “the patron saint of feminist dystopian fiction” (The New York Times). Now an award-winning Hulu series starring Elizabeth Moss.',
                                 url='https://prodimage.images-bn.com/pimages/9780385490818_p0_v5_s550x406.jpg')
    book17.category.set([parent1, category1])

    book18 = Book.objects.create(author=author14,
                                 title='A Court of Frost and Starlight',
                                 price='25.99',
                                 first_published=2020,
                                 description='Feyre, Rhysand, and their friends are still busy rebuilding the Night Court and the vastly altered world beyond, recovering from the war that changed everything. But Winter Solstice is finally approaching, and with it, the joy of a hard-earned reprieve. ',
                                 url='https://prodimage.images-bn.com/pimages/9781635575620_p0_v2_s550x406.jpg')
    book18.category.set([parent1, category1])

    book19 = Book.objects.create(author=author16,
                                 title='The Invisible Life of Addie LaRue',
                                 price='22.99',
                                 first_published=2020,
                                 description='A Life No One Will Remember. A Story You Will Never Forget. France, 1714: in a moment of desperation, a young woman makes a Faustian bargain to live forever—and is cursed to be forgotten by everyone she meets.Thus begins the extraordinary life of Addie LaRue, and a dazzling adventure that will play out across centuries and continents, across history and art, as a young woman learns how far she will go to leave her mark on the world.',
                                 url='https://prodimage.images-bn.com/pimages/9780765387561_p0_v4_s550x406.jpg')
    book19.category.set([parent1, category1])

    book20 = Book.objects.create(author=author17,
                                 title='One Good Deed (An Archer Novel)',
                                 price='25.99',
                                 first_published=2019,
                                 description='It\'s 1949. When war veteran Aloysius Archer is released from Carderock Prison, he is sent to Poca City on parole with a short list of do\'s and a much longer list of don\'ts: do report regularly to his parole officer, don\'t go to bars, certainly don\'t drink alcohol, do get a job -- and don\'t ever associate with loose women',
                                 url='https://m.media-amazon.com/images/I/51oxNo6r0TL.jpg')
    book20.category.set([parent1, category2])

    book21 = Book.objects.create(author=author17,
                                 title='A Gambling Man(An Archer Novel Book 2)',
                                 price='29.99',
                                 first_published=2021,
                                 description='Along the way, Archer stops in Reno, where a stroke of fortune delivers him a wad of cash and an eye-popping blood-red 1939 Delahaye convertible—plus a companion for the final leg of the journey, an aspiring actress named Liberty Callahan who is planning to try her luck in Hollywood. But when the two arrive in Bay Town, California, Archer quickly discovers that the hordes of people who flocked there seeking fame and fortune landed in a false paradise that instead caters to their worst addictions and fears.',
                                 url='https://m.media-amazon.com/images/I/514TEwu5BkS.jpg')
    book21.category.set([parent1, category2])

    book22 = Book.objects.create(author=author18,
                                 title='Harry Potter and the Chamber of Secrets',
                                 price='30.99',
                                 first_published=2015,
                                 description='Harry Potter\'s summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone... Dobby\'s sinister predictions seem to be coming true.',
                                 url='https://m.media-amazon.com/images/I/51TA3VfN8RL.jpg')
    book22.category.set([parent1, category2])

    book23 = Book.objects.create(author=author18,
                                 title='Harry Potter and the Order of the Phoenix',
                                 price='15.99',
                                 first_published=2015,
                                 description='Dark times have come to Hogwarts. After the Dementors\' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord\'s return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort\'s savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time.',
                                 url='https://m.media-amazon.com/images/I/51-SI2+aQ2L.jpg')
    book23.category.set([parent1, category2])

    book24 = Book.objects.create(author=author19,
                                 title='The Sentinel: (Jack Reacher 25)',
                                 price='14.99',
                                 first_published=2020,
                                 description='Jack Reacher gets off the bus in a sleepy no-name town outside Nashville, Tennessee. He plans to grab a cup of coffee and move right along.Not going to happen.The town has been shut down by a cyber attack. At the centre of it all, whether he likes it or not, is Rusty Rutherford. He\'s an average IT guy, but he knows more than he thinks.',
                                 url='https://m.media-amazon.com/images/I/51SSDIq7n8L.jpg')
    book24.category.set([parent1, category2])

    book25 = Book.objects.create(author=author20,
                                 title='At the Wolf\'s Table: A Novel',
                                 price='14.99',
                                 first_published=2020,
                                 description='They called it the Wolfsschanze, the Wolf’s Lair. “Wolf” was his nickname. As hapless as Little Red Riding Hood, I had ended up in his belly. A legion of hunters was out looking for him, and to get him in their grips they would gladly slay me as well.',
                                 url='https://prodimage.images-bn.com/pimages/9781250179166_p0_v2_s550x406.jpg')
    book25.category.set([parent1, category3])

    book26 = Book.objects.create(author=author21,
                                 title='The Light after the War',
                                 price='24.99',
                                 first_published=2020,
                                 description='It is 1946 when Vera Frankel and her best friend Edith Ban arrive in Naples. Refugees from Hungary, they managed to escape from a train headed for Auschwitz and spent the rest of the war hiding on an Austrian farm. Now, the two young women must start new lives abroad. Armed with a letter of recommendation from an American officer, Vera finds work at the United States embassy where she falls in love with Captain Anton Wight.',
                                 url='https://prodimage.images-bn.com/pimages/9781982122973_p0_v3_s550x406.jpg')
    book26.category.set([parent1, category3])

    book27 = Book.objects.create(author=author22,
                                 title='The Other Einstein',
                                 price='15.99',
                                 first_published=2016,
                                 description='In the tradition of Beatriz Williams and Paula McClain, Marie Benedict\'s The Other Einstein offers us a window into a brilliant, fascinating woman whose light was lost in Einstein\'s enormous shadow. This novel resurrects Einstein\'s wife, a brilliant physicist in her own right, whose contribution to the special theory of relativity is hotly debated. Was she simply Einstein\'s sounding board, an assistant performing complex mathematical equations? Or did she contribute something more?',
                                 url='https://prodimage.images-bn.com/pimages/9781492637264_p0_v4_s550x406.jpg')
    book27.category.set([parent1, category3])

    book28 = Book.objects.create(author=author23,
                                 title='The Girls with No Names',
                                 price='12.99',
                                 first_published=2020,
                                 description='A beautiful tale of hope, courage, and sisterhood—inspired by the real House of Mercy and the girls confined there for daring to break the rules. Growing up in New York City in the 1910s, Luella and Effie Tildon realize that even as wealthy young women, their freedoms come with limits. But when the sisters discover a shocking secret about their father, Luella, the brazen elder sister, becomes emboldened to do as she pleases. Her rebellion comes with consequences, and one morning Luella is mysteriously gone.',
                                 url='https://prodimage.images-bn.com/pimages/9781488050992_p0_v2_s550x406.jpg')
    book28.category.set([parent1, category3])

    book29 = Book.objects.create(author=author24,
                                 title='The Land Beyond the Sea',
                                 price='16.99',
                                 first_published=2020,
                                 description='The Kingdom of Jerusalem, also known as Outremer, is the land far beyond the sea. Baptized in blood when the men of the First Crusade captured Jerusalem from the Saracens in the early twelfth century, the kingdom defined an utterly new world, a land of blazing heat and a medley of cultures, a place where enemies were neighbors and neighbors became enemies.',
                                 url='https://prodimage.images-bn.com/pimages/9781101621752_p0_v2_s550x406.jpg')
    book29.category.set([parent1, category3])

    book30 = Book.objects.create(author=author25,
                                 title='Pillow Thoughts',
                                 price='15.99',
                                 first_published=2017,
                                 description='Pillow Thoughts is a collection of poetry and prose about heartbreak, love, and raw emotions. It is divided into sections to read when you feel you need them most.',
                                 url='https://prodimage.images-bn.com/pimages/9781449489755_p0_v1_s550x406.jpg')
    book30.category.set([parent1, category4])

    book31 = Book.objects.create(author=author25,
                                 title='Pillow Thoughts II: Healing the Heart',
                                 price='22.99',
                                 first_published=2018,
                                 description='Pillow Thoughts is a collection of poetry and prose about heartbreak, love, and raw emotions. It is divided into sections to read when you feel you need them most.Make a cup of tea and let yourself feel.',
                                 url='https://prodimage.images-bn.com/pimages/9781449498047_p0_v2_s550x406.jpg')
    book31.category.set([parent1, category4])

    book32 = Book.objects.create(author=author26,
                                 title='All Along You Were Blooming: Thoughts for Boundless Living',
                                 price='20.99',
                                 first_published=2020,
                                 description='A celebration of hope. An encounter with grace. A restoration of the heart. A healing of wounds. An anthem of freedom. All Along You Were Blooming is the ultimate love letter from the pen of popular Instagram poet Morgan Harper Nichols to your mind, heart, soul, and body.',
                                 url='https://prodimage.images-bn.com/pimages/9780310454076_p0_v3_s550x406.jpg')
    book32.category.set([parent1, category4])

    book33 = Book.objects.create(author=author26,
                                 title='How Far You Have Come: Musings on Beauty and Courage',
                                 price='15.99',
                                 first_published=2021,
                                 description='How Far You Have Come is an exquisitely illustrated collection of poetry and essays from bestselling artist and writer Morgan Harper Nichols. In the midst of the hurt and the mundane, the questions and the not yets, we can forget just how far we have come. Morgan weaves together personal reflections with her signature poems to share her journey to reclaim moments of brokenness, division, and pain and re-envision them as experiences of reconciliation, unity, and hope.',
                                 url='https://prodimage.images-bn.com/pimages/9780310456599_p0_v3_s550x406.jpg')
    book33.category.set([parent1, category4])

    book34 = Book.objects.create(author=author27,
                                 title='Dog Songs',
                                 price='14.99',
                                 first_published=2015,
                                 description='Mary Oliver’s Dog Songs is a celebration of the special bond between human and dog, as understood through the poet’s relationships to the canines that have accompanied her daily walks, warmed her home, and inspired her work. Oliver’s poems begin in the small everyday moments familiar to all dog lovers, but through her extraordinary vision, these observations become higher meditations on the world and our place in it.',
                                 url='https://prodimage.images-bn.com/pimages/9780143125839_p0_v1_s550x406.jpg')
    book34.category.set([parent1, category4])

    book35 = Book.objects.create(author=author28,
                                 title='Star Wars:Thrawn Ascendancy',
                                 price='29.99',
                                 first_published=2021,
                                 description='Thrawn’s latest triumph still rests newly on his shoulders. He has led the Chiss to victory and brought glory to the House of Mitth, but the true threat to the Ascendancy has not yet been extinguished. Their foes do not send threats or ultimatums, do not mass ships on the edge of the Chaos. Their weapons come cloaked in smiles and generosity: Gifts offered freely. Services granted unconditionally.',
                                 url='https://prodimage.images-bn.com/pimages/9780593358153_p0_v2_s550x406.jpg')
    book35.category.set([parent1, category5])

    book36 = Book.objects.create(author=author28,
                                 title='Thrawn (Star Wars)',
                                 price='19.99',
                                 first_published=2018,
                                 description='One of the most cunning and ruthless warriors in the history of the Galactic Empire, Grand Admiral Thrawn is also one of the most captivating characters in the Star Wars universe, from his introduction in bestselling author Timothy Zahn’s classic Heir to the Empire through his continuing adventures in Dark Force Rising, The Last Command, and beyond. But Thrawn’s origins and the story of his rise in the Imperial ranks have remained mysterious.',
                                 url='https://prodimage.images-bn.com/pimages/9781101967027_p0_v2_s550x406.jpg')
    book36.category.set([parent1, category5])

    book37 = Book.objects.create(author=author13,
                                 title='Drums of Autumn',
                                 price='15.99',
                                 first_published=2004,
                                 description='What if you knew someone you loved was going to die? What if you thought you could save them? How much would you risk to try? Claire Randall has gone to find Jamie Fraser, the man she loved more than life, and has left half her heart behind with their daughter, Brianna. Claire gave up Jamie to save Brianna, and now Bree has sent her mother back to the mysterious Scottish warrior who was willing to give his life to save them both. ',
                                 url='https://prodimage.images-bn.com/pimages/9780440335177_p0_v4_s550x406.jpg')
    book37.category.set([parent1, category5])

    book38 = Book.objects.create(author=author29,
                                 title='The Only Good Indians',
                                 price='19.99',
                                 first_published=2021,
                                 description='At the crossroads of horror, poetry and history sits The Only Good Indians. These three paths might seem inconceivable considering the first road mentioned. No talk here of what will keep you up at night. “Poetic” should be called out in Jones’ writing. He gives distinct voice to his four main characters. ',
                                 url='https://prodimage.images-bn.com/pimages/9781982136468_p0_v3_s550x406.jpg')
    book38.category.set([parent1,category6, category11])

    book39 = Book.objects.create(author=author29,
                                 title='The Last Final Girl',
                                 price='14.99',
                                 first_published=2012,
                                 description='The Last Final Girl is like Quentin Tarantino\'s take on The Cabin in the Woods. Bloody, absurd, and smart. Plus, there\'s a killer in a Michael Jackson mask." - Carlton Mellick III, author of ApeshitLife in a slasher film is easy. You just have to know when to die.',
                                 url='https://prodimage.images-bn.com/pimages/9781621050513_p0_v2_s550x406.jpg')
    book39.category.set([parent1, category6, category11])


    book40 = Book.objects.create(author=author30,
                                 title='Hard Cash Valley',
                                 price='20.99',
                                 first_published=2021,
                                 description='Dane Kirby is a broken man and no stranger to tragedy. As a life-long resident and ex-arson investigator for McFalls County, Dane has lived his life in one of the most chaotic and crime-ridden regions of the south. When he gets called in to consult on a brutal murder in a Jacksonville, Florida, motel room, he and his FBI counterpart, Special Agent Roselita Velasquez, begin an investigation that leads them back to the criminal circles of his own backyard.',
                                 url='https://prodimage.images-bn.com/pimages/9781250779632_p0_v6_s550x406.jpg')
    book40.category.set([parent1, category7, category11])

    book41 = Book.objects.create(author=author31,
                                 title='Gold Mine Massacre',
                                 price='12.99',
                                 first_published=2021,
                                 description='For Smoke and his daughter Denny, life on the Sugarloaf Ranch is more valuable than all the gold in the world. Which works out fine, since all the gold mines in Big Rock were squeezed dry years ago. Even so, that won’t stop a pair of businessmen from the East from trying to squeeze out a little more.',
                                 url='https://prodimage.images-bn.com/pimages/9780786047307_p0_v1_s550x406.jpg')

    book41.category.set([parent1, category8])

    book42 = Book.objects.create(author=author31,
                                 title='Red River Vengeance',
                                 price='15.99',
                                 first_published=2021,
                                 description='A good man like Perley Gates knows that when you race with the devil, you\'d better cross the finish line first—or you won\'t finish at all...',
                                 url='https://prodimage.images-bn.com/pimages/9780786047390_p0_v1_s550x406.jpg')
    book42.category.set([parent1, category8])

    book43 = Book.objects.create(author=author31,
                                 title='By the Neck',
                                 price='14.99',
                                 first_published=2021,
                                 description='Rollie Finnegan is a man of few words. As a former Pinkerton agent with two decades of experience under his belt, he uses his stony silence to break down suspects and squeeze out confessions. Hence the nickname Stoneface. Over the years, he’s locked up plenty of killers. Now he’s ready to make a killing—for himself.',
                                 url='https://prodimage.images-bn.com/pimages/9780786046058_p0_v2_s550x406.jpg')
    book43.category.set([parent1, category8])

    book44 = Book.objects.create(author=author32,
                                 title='Outlawed',
                                 price='25.99',
                                 first_published=2021,
                                 description='The Crucible meets True Grit in this riveting adventure story of a fugitive girl, a mysterious gang of robbers, and their dangerous mission to transform the Wild West.',
                                 url='https://prodimage.images-bn.com/pimages/9781635575422_p0_v6_s550x406.jpg')
    book44.category.set([parent1, category8, category11])

    book45 = Book.objects.create(author=author32,
                                 title='The Life and Death of Sophie Stark',
                                 price='15.99',
                                 first_published=2016,
                                 description='Who is Sophie Stark? A brilliant filmmaker, a lover, a wife, a friend, a traitor. A troubled misfit who becomes a star, at great cost to the people who love her and, ultimately, to herself. Gripping and provocative, The Life and Death of Sophie Stark is a story of the power of art to transform lives and to destroy them, and of an artist’s drive to create something greater than herself, even if it means sacrificing everything—and everyone—she loves.',
                                 url='https://prodimage.images-bn.com/pimages/9780399184475_p0_v2_s550x406.jpg')
    book45.category.set([parent1, category8])

    book46 = Book.objects.create(author=author32,
                                 title='America Pacifica',
                                 price='19.99',
                                 first_published=2012,
                                 description='Eighteen-year-old Darcy lives on the island of America Pacifica--one of the last places on earth that is still habitable, after North America has succumbed to a second ice age. Education, food, and basic means of survival are the province of a chosen few, while the majority of the island residents must struggle to stay alive. ',
                                 url='https://prodimage.images-bn.com/pimages/9780316105071_p0_v3_s550x406.jpg')
    book46.category.set([parent1, category8])

    book47 = Book.objects.create(author=author33,
                                 title='The Forgotten 500',
                                 price='29.99',
                                 first_published=2008,
                                 description='During a bombing campaign over Romanian oil fields, hundreds of American airmen were shot down in Nazi-occupied Yugoslavia. Local Serbian farmers and peasants risked their own lives to give refuge to the soldiers while they waited for rescue, and in 1944, Operation Halyard was born. The risks were incredible. The starving Americans in Yugoslavia had to construct a landing strip large enough for C-47 cargo planes—without tools, without alerting the Germans, and without endangering the villagers. And the cargo planes had to make it through enemy airspace and back—without getting shot down themselves.',
                                 url='https://images-na.ssl-images-amazon.com/images/I/51DWVP8UvBL._SX330_BO1,204,203,200_.jpg')
    book47.category.set([parent1, category25])

    book48 = Book.objects.create(author=author33,
                                 title='The Wooden Horse',
                                 price='20.99',
                                 first_published=2004,
                                 description='An epic adventure the most brilliant escape and evasion from the Nazis ever written.',
                                 url='https://images-na.ssl-images-amazon.com/images/I/81Dy8j0pWOL.SR160,240_BG243,243,243.jpg')
    book48.category.set([parent1, category25])

    book48 = Book.objects.create(author=author34,
                                 title='A Higher Call',
                                 price='15.99',
                                 first_published=2014,
                                 description='A “beautiful story of a brotherhood between enemies” emerges from the horrors of World War II in this New York Times bestseller by the author of Spearhead. ',
                                 url='https://images-na.ssl-images-amazon.com/images/I/51WmMXXbi4L._SX329_BO1,204,203,200_.jpg')
    book48.category.set([parent1, category25])

    book49 = Book.objects.create(author=author35,
                                 title='Naruto, Volume 1',
                                 price='10.99',
                                 first_published=2003,
                                 description='Naruto is a young shinobi with an incorrigible knack for mischief. He’s got a wild sense of humor, but Naruto is completely serious about his mission to be the world’s greatest ninja!',
                                 url='https://prodimage.images-bn.com/pimages/9781569319000_p0_v1_s550x406.jpg')
    book49.category.set([parent1, category26])

    book50 = Book.objects.create(author=author35,
                                 title='Naruto, Volume 2',
                                 price='10.99',
                                 first_published=2003,
                                 description='Tired of menial tasks, Naruto, Sasuke and Sakura ask for a tougher assignment. But you should always be careful what you wish for! Along with their teacher, Kakashi, the trio must now guard a cranky old man from the Land of the Waves. But Tazuna the bridgebuilder is in more danger than anyone could have imagined. And now the young ninja are too!',
                                 url='https://prodimage.images-bn.com/pimages/9781591161783_p0_v1_s550x406.jpg')
    book50.category.set([parent1, category26])

    book51 = Book.objects.create(author=author35,
                                 title='Naruto, Volume 3',
                                 price='15.99',
                                 first_published=2011,
                                 description='Naruto\'s sensei Kakashi believes that the diablolical Zabuza survived their last battle. Now, in anticipation of their enemy\'s return, Kakashi puts Naruto, Sasuke and Sakura through rigorous training programs to increase their focus and control. This time, the job of protecting the old bridge builder Tazuna and his family will be a hundred times more difficult!',
                                 url='https://prodimage.images-bn.com/pimages/9781421544366_p0_v1_s550x406.jpg')
    book51.category.set([parent1, category26])

    book52 = Book.objects.create(author=author35,
                                 title='Naruto, Volume 4',
                                 price='19.99',
                                 first_published=2011,
                                 description='In the Land of Waves, Naruto and his teammates Sakura and Sasuke, along with their sensei Kakashi, struggle to protect the bridge builder Tazuna and his family from Gato\'s hired thugs. When one of Naruto\'s friends falls in battle, Naruto is faced with the most difficult choice of his life. How far will he go to protect his friends? And does he have what it takes to be a hero?',
                                 url='https://prodimage.images-bn.com/pimages/9781421544410_p0_v1_s550x406.jpg')
    book52.category.set([parent1, category26])

    book53 = Book.objects.create(author=author35,
                                 title='Naruto, Volume 5',
                                 price='10.99',
                                 first_published=2004,
                                 description='Naruto is a young shinobi with an incorrigible knack for mischief. He’s got a wild sense of humor, but Naruto is completely serious about his mission to be the world’s greatest ninja!',
                                 url='https://prodimage.images-bn.com/pimages/9781591163596_p0_v2_s550x406.jpg')
    book53.category.set([parent1, category26])

    book54 = Book.objects.create(author=author35,
                                 title='Naruto, Volume 6',
                                 price='15.99',
                                 first_published=2011,
                                 description='Naruto, Sasuke and Sakura passed the written portion of the Chûnin Exam, but that was only the beginning! Now in the thick of the exam\'s second phase, held in the aptly named Forest of Death, instructor Mitarashi Anko has promised to cut the number of advancing teams by half. And a mysterious predator in their midst is after Sasuke!',
                                 url='https://prodimage.images-bn.com/pimages/9781421544458_p0_v1_s550x406.jpg')
    book54.category.set([parent1, category26])

    book54 = Book.objects.create(author=author35,
                                 title='Naruto, Volume 7',
                                 price='15.99',
                                 first_published=2011,
                                 description='Deep within the Forest of Death, Naruto, Sasuke and Sakura are still reeling from Orochimaru\'s attack...and now they must battle his minions, the mysterious Sound Ninja. And as Sasuke struggles with the strange force growing inside him, spreading like an infection from the curse-mark Orochimaru burned into his neck, time is running out for the student ninja to collect the scrolls they need to pass the Chûnin Exams!',
                                 url='https://prodimage.images-bn.com/pimages/9781421544465_p0_v1_s550x406.jpg')
    book54.category.set([parent1, category26])

    book55 = Book.objects.create(author=author35,
                                 title='Naruto, Volume 8',
                                 price='16.99',
                                 first_published=2011,
                                 description='As the preliminaries to the third phase of the Journeyman Ninja Selection Exams begin, the student ninja face off against each other in no-holds-barred, one-on-one bouts. Deaf to Sakura\'s pleas to withdraw from the contest and despite the crippling effects of the curse placed on him by the nefarious Orochimaru, Sasuke enters the first match against one of the vicious Sound Ninja spies.',
                                 url='https://prodimage.images-bn.com/pimages/9781421544472_p0_v1_s550x406.jpg')
    book55.category.set([parent1, category26])

    book56 = Book.objects.create(author=author35,
                                 title='Naruto, Volume 9',
                                 price='14.99',
                                 first_published=2011,
                                 description='The student ninja unleash their signature moves as the preliminaries to the third phase of the Chûnin Exams continue. The heated, one-on-one battles bring out the best and the worst in the young ninja fighting to move on to the finals. When Hyuga clan members Neji and Hinata are pitted against each other, will old family grudges make their duel more vicious than the rest?',
                                 url='https://prodimage.images-bn.com/pimages/9781421544489_p0_v1_s550x406.jpg')
    book56.category.set([parent1, category26])

    book57 = Book.objects.create(author=author36,
                                 title='Bleach, Vol. 1: Strawberry and the Soul Reapers',
                                 price='10.99',
                                 first_published=2004,
                                 description='Part-time student, full-time Soul Reaper, Ichigo is one of the chosen few guardians of the afterlife.Ichigo Kurosaki never asked for the ability to see ghosts—he was born with the gift. When his family is attacked by a Hollow—a malevolent lost soul—Ichigo becomes a Soul Reaper, dedicating his life to protecting the innocent and helping the tortured spirits themselves find peace. Find out why Tite Kubo’s Bleach has become an international manga smash-hit!',
                                 url='https://prodimage.images-bn.com/pimages/9781591164418_p0_v1_s550x406.jpg')
    book57.category.set([parent1, category26])

    book58 = Book.objects.create(author=author36,
                                 title='Bleach, Vol. 2: Goodbye Parakeet, Good Night My Sister',
                                 price='10.99',
                                 first_published=2004,
                                 description='chigo Kurosaki never asked for the ability to see ghosts—he was born with the gift. When his family is attacked by a Hollow—a malevolent lost soul—Ichigo becomes a Soul Reaper, dedicating his life to protecting the innocent and helping the tortured spirits themselves find peace. Find out why Tite Kubo’s Bleach has become an international manga smash-hit!',
                                 url='https://prodimage.images-bn.com/pimages/9781591164425_p0_v2_s550x406.jpg')
    book58.category.set([parent1, category26])

    book59 = Book.objects.create(author=author36,
                                 title='Bleach (3-in-1 Edition), Vol. 3: Includes Vols. 10, 11 & 12',
                                 price='15.99',
                                 first_published=2011,
                                 description='Rukia Kuchiki, the ex-Soul Reaper responsible for Ichigo\'s transformation, is on the lam. Her brethren at the Soul Society are quite displeased with the fact that she transferred the powers of a Soul Reaper to a human and have dispatched two of their strongest agents to neutralize the situation. Their mission is twofold: to return Rukia to the Soul Society so that she may pay for her crime and to deal with Ichigo—permanently. But an unlikely third party is standing in their way: Uryû Ishida, the Quincy!',
                                 url='https://prodimage.images-bn.com/pimages/9781421539942_p0_v2_s550x406.jpg')
    book59.category.set([parent1, category26])

    book60 = Book.objects.create(author=author36,
                                 title='Bleach (3-in-1 Edition), Vol. 4: Includes Vols. 10, 11 & 12',
                                 price='17.99',
                                 first_published=2013,
                                 description='Ichigo and crew are determined to rescue Rukia from the Soul Society, and with the help of explosives expert Kûkaku, they actually have a chance of making it inside the walls. But the plan hinges on Ichigo getting control of his torrential spiritual energy, and with Rukia awaiting execution, there’s no time to waste! And even if they can breach the Soul Society’s defenses, there are twelve companies of angry Soul Reapers standing between them and their friend!',
                                 url='https://prodimage.images-bn.com/pimages/9781421554679_p0_v3_s550x406.jpg')
    book60.category.set([parent1, category26])

    book61 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 1',
                                 price='10.99',
                                 first_published=2012,
                                 description='In this post-apocalytpic sci-fi story, humanity has been devastated by the bizarre, giant humanoids known as the Titans. Little is known about where they came from or why they are bent on consuming mankind. Seemingly unintelligent, they have roamed the world for years, killing everyone they see. For the past century, what\'s left of man has hidden in a giant, three-walled city. People believe their 50-meter-high walls will protect them from the Titans, but the sudden appearance of an immense Titan is about to change everything.',
                                 url='https://prodimage.images-bn.com/pimages/9781612620244_p0_v2_s550x406.jpg')
    book61.category.set([parent1, category9])

    book62 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 2',
                                 price='10.99',
                                 first_published=2012,
                                 description='The Colossal Titan has breached humanity’s first line of defense, Wall Maria. Mikasa, the 104th Training Corps’ ace and Eren’s best friend, may be the only one capable of defeating them, but beneath her calm exterior lurks a dark past. When all looks lost, a new Titan appears and begins to slaughter its fellow Titans. Could this new monster be a blessing in disguise, or is the truth something much more sinister?',
                                 url='https://prodimage.images-bn.com/pimages/9781612620251_p0_v2_s550x406.jpg')
    book62.category.set([parent1, category9])

    book63 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 3',
                                 price='10.99',
                                 first_published=2012,
                                 description='The last thing Eren remembers before blacking out, a Titan had bitten off his arm and leg and was getting ready to eat him alive. Much to his surprise he wakes up without a scratch on him, with a crowd of angry soldiers screaming for his blood. What strange new power has he awakened, and what will happen when the boy devoted to destroying the Titans becomes one himself?',
                                 url='https://prodimage.images-bn.com/pimages/9781612620268_p0_v2_s550x406.jpg')
    book63.category.set([parent1, category9])

    book64 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 4',
                                 price='10.99',
                                 first_published=2013,
                                 description='he Survey Corps develop a risky gambit – have Eren in Titan form attempt to repair Wall Rose, reclaiming human territory from the monsters for the first time in a century. But Titan-Eren’s self-control is far from perfect, and when he goes on a rampage, not even Armin can stop him! With the survival of humanity on his massive shoulders, will Eren be able to return to his senses, or will he lose himself forever?',
                                 url='https://prodimage.images-bn.com/pimages/9781612622538_p0_v1_s550x406.jpg')
    book64.category.set([parent1, category9])

    book65 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 5',
                                 price='10.99',
                                 first_published=2013,
                                 description='Thanks to Eren, humanity has taken the town of Trost back from the Titans. Exhausted, Eren falls into a coma for three days – and wakes in shackles, staring at Erwin Smith, leader of the Survey Corps. Certain that Eren’s father’s research holds the key to the mystery of the Titans’ rise, Smith wants an expedition to retrieve it from the house where Eren grew up. But that’s deep in Titan territory, and to get there Eren will need to master a power he still doesn’t fully understand…',
                                 url='https://prodimage.images-bn.com/pimages/9781612622545_p0_v1_s550x406.jpg')
    book65.category.set([parent1, category9])

    book66 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 6',
                                 price='10.99',
                                 first_published=2013,
                                 description='On the way to Eren’s home, deep in Titan territory, the Survey Corps ranks are broken by a charge led by a female Titan! But this Abnormal is different – she kills not to eat but to protect herself, and she seems to be looking for someone. Armin comes to a shocking conclusion: She’s a human in a Titan’s body, just like Eren!',
                                 url='https://prodimage.images-bn.com/pimages/9781612622552_p0_v1_s550x406.jpg')
    book66.category.set([parent1, category9])

    book67 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 7',
                                 price='10.99',
                                 first_published=2013,
                                 description='The Survey Corps sets a cunning trap to capture the mysterious Abnormal Titan that broke through their ranks. As Armin tries to determine the grotesque creature’s identity and purpose, scouts report Titans closing in on all sides! But they don’t seem to be after the humans – instead they’re targeting the Titan!',
                                 url='https://prodimage.images-bn.com/pimages/9781612622569_p0_v1_s550x406.jpg')
    book67.category.set([parent1, category9])

    book68 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 8',
                                 price='10.99',
                                 first_published=2013,
                                 description='The expedition outside the wall was Eren\'s chance to prove himself. But it failed, and the female Titan is free once more! With his squad dead, Eren faces a royal summons. Will Mikasa and Armin have to betray their king to save their friend? And can they discover the female Titan\'s identity before she kills again?',
                                 url='https://prodimage.images-bn.com/pimages/9781612625478_p0_v1_s550x406.jpg')
    book68.category.set([parent1, category9])

    book69 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 9',
                                 price='10.99',
                                 first_published=2013,
                                 description='Eren is still resting from his brutal fight with the female Titan, when word reaches the interior that the impossible has happened: Wall Rose itself has been breached, and Titans are pouring through the gap! The emergency casts new urgency over Armin and Hange\'s questions about how the walls were built, and what humanity can do to restore them...',
                                 url='https://prodimage.images-bn.com/pimages/9781612625485_p0_v1_s550x406.jpg')
    book69.category.set([parent1, category9])

    book70 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 10',
                                 price='10.99',
                                 first_published=10.99,
                                 description='With no combat gear and Wall Rose breached, the 104th scrambles to evacuate the villages in the Titans\' path. On their way to the safety of Wall Sheena, they decide to spend the night in Utgard Castle. But their sanctuary becomes a slaughterhouse when they discover that, for some reason, these Titans attack at night!',
                                 url='https://prodimage.images-bn.com/pimages/9781612626765_p0_v1_s550x406.jpg')
    book70.category.set([parent1, category9])

    book71 = Book.objects.create(author=author37,
                                 title='Attack on Titan, Volume 11',
                                 price='10.99',
                                 first_published=2014,
                                 description='Thanks to Eren\'s timely arrival, the 104th has managed to turn the tide at Wall Rose. But this momentary victory forces two more traitors into a corner – and the identity of the Titans who have been destroying the walls is revealed! What can Eren do against the two most dangerous monsters humanity has ever faced? And who else might be an enemy in disguise?',
                                 url='https://prodimage.images-bn.com/pimages/9781612626772_p0_v1_s550x406.jpg')
    book71.category.set([parent1, category9])

    book72 = Book.objects.create(author= author38,
                                 title='Verity',
                                 price='15.99',
                                 first_published=2018,
                                 description='owen Ashleigh is a struggling writer on the brink of financial ruin. When Jeremy Crawford, husband of bestselling author Verity Crawford, asks Lowen to complete the remaining books in a contract his permanently injured wife is unable to fulfill, Lowen has no choice but to accept. Lowen arrives at the Crawford home with the intention of only staying one or two nights-long enough to sort through Verity\'s chaotic home office to collect all the notes and outlines she\'ll need to start writing the first novel.',
                                 url='https://prodimage.images-bn.com/pimages/9781791392796_p0_v6_s550x406.jpg')
    book72.category.set([parent1, category10])

    book73 = Book.objects.create(author=author38,
                                 title='Maybe Someday',
                                 price='15.99',
                                 first_published=2014,
                                 description='At twenty-two years old, Sydney is enjoying a great life: She’s in college, working a steady job, in love with her wonderful boyfriend, Hunter, and rooming with her best friend, Tori. But everything changes when she discovers that Hunter is cheating on her—and she’s forced to decide what her next move should be.',
                                 url='https://prodimage.images-bn.com/pimages/9781476753164_p0_v4_s550x406.jpg')
    book73.category.set([parent1, category10])

    book74 = Book.objects.create(author=author38,
                                 title='Regretting You',
                                 price='17.99',
                                 first_published=2019,
                                 description='Morgan Grant and her sixteen-year-old daughter, Clara, would like nothing more than to be nothing alike.Morgan is determined to prevent her daughter from making the same mistakes she did. By getting pregnant and married way too young, Morgan put her own dreams on hold. Clara doesn’t want to follow in her mother\’s footsteps. Her predictable mother doesn’t have a spontaneous bone in her body.',
                                 url='https://prodimage.images-bn.com/pimages/9781542016421_p0_v2_s550x406.jpg')
    book74.category.set([parent1, category10])

    book75 = Book.objects.create(author=author39,
                                 title='Shadow Storm',
                                 price='10.99',
                                 first_published=2021,
                                 description='As the youngest member of the Ferraro family, Emmanuelle has watched each of her brothers find happiness in love while her own heart was shattered by a lover’s betrayal. For two years she’s stayed as far away from Valentino Saldi as possible—until she learns that he’s been shot during a hostile takeover of his family’s territory.',
                                 url='https://prodimage.images-bn.com/pimages/9780593333136_p0_v2_s550x406.jpg')
    book75.category.set([parent1, category10])

    book76 = Book.objects.create(author=author39,
                                 title='Reckless Road',
                                 price='10.99',
                                 first_published=2021,
                                 description='While Gedeon “Player” Lazaroff is one of Torpedo Ink motorcycle club’s roughest members, he’s also one of the calmest. Little rattles Player, except for the times his gift gets the better of him. When that happens, he has to just lie down in the dark and hope for the best. But on a night when he’s on the verge of losing it, he meets a woman who manages to soothe his fractured mind.',
                                 url='https://prodimage.images-bn.com/pimages/9780593099865_p0_v2_s550x406.jpg')
    book76.category.set([parent1, category10])

    book77 = Book.objects.create(author=author34,
                                 title='Voices of the Pacific',
                                 price='30.99',
                                 first_published=2021,
                                 description='Following fifteen Marines from Pearl Harbor, through their battles with the Japanese, to their return home after V-J Day, Adam Makos and Marcus Brotherton have compiled an oral history of the Pacific War in the words of the men who fought on the front lines. With vivid, unforgettable detail, these Marines reveal harrowing accounts of combat with an implacable enemy, the camaraderie they found, the friends they lost, and the aftermath of the war\'s impact on their lives.',
                                 url='https://prodimage.images-bn.com/pimages/9780593185315_p0_v2_s550x406.jpg')
    book77.category.set([parent1, category25])

    #Non Fiction books
    #Art/arhitecture&Photography category
    book78 = Book.objects.create(author=author40,
                                 title='The Lost Spells',
                                 price='25.99',
                                 first_published=2020,
                                 description='The Lost Spells evokes the wonder of everyday nature, conjuring up red foxes, birch trees, jackdaws, and more in poems and illustrations that flow between the pages and into readers’ minds. Robert Macfarlane’s spell-poems and Jackie Morris’s watercolour illustrations are musical and magical: these are summoning spells, words of recollection, charms of protection. To read The Lost Spells is to see anew the natural world within our grasp and to be reminded of what happens when we allow it to slip away.',
                                 url='https://prodimage.images-bn.com/pimages/9781487007799_p0_v20_s550x406.jpg')
    book78.category.set([parent2, category12])

    book79 = Book.objects.create(author=author40,
                                 title='The Lost Words',
                                 price='31.99',
                                 first_published=2018,
                                 description='Ten years later, Robert Macfarlane and Jackie Morris set out to make a “spell book” that will conjure back twenty of these lost words, and the beings they name, from acorn to wren. By the magic of word and paint, they sought to summon these words again into the voices, stories, and dreams of children and adults alike, and to celebrate the wonder and importance of everyday nature. ',
                                 url='https://prodimage.images-bn.com/pimages/9781487005382_p0_v1_s550x406.jpg')
    book79.category.set([parent2, category12])

    book80 = Book.objects.create(author=author41,
                                 title='The Devil in the White City: Murder, Magic, and Madness at the Fair That Changed America',
                                 price='21.99',
                                 first_published=2004,
                                 description='The Devil in the White City draws the reader into a time of magic and majesty, made all the more appealing by a supporting cast of real-life characters, including Buffalo Bill, Theodore Dreiser, Susan B. Anthony, Thomas Edison, Archduke Francis Ferdinand, and others. Erik Larson’s gifts as a storyteller are magnificently displayed in this rich narrative of the master builder, the killer, and the great fair that obsessed them both.',
                                 url='https://prodimage.images-bn.com/pimages/9780375725609_p0_v3_s550x406.jpg')
    book80.category.set([parent2, category12])

    book81 = Book.objects.create(author=author41,
                                 title='In the Garden of Beasts: Love, Terror, and an American Family in Hitler\'s Berlin',
                                 price='17.99',
                                 first_published=2012,
                                 description='The time is 1933, the place, Berlin, when William E. Dodd becomes America’s first ambassador to Hitler’s Nazi Germany in a year that proved to be a turning point in history. A mild-mannered professor from Chicago, Dodd brings along his wife, son, and flamboyant daughter, Martha. At first Martha is entranced by the parties and pomp, and the handsome young men of the Third Reich with their infectious enthusiasm for restoring Germany to a position of world prominence. ',
                                 url='https://prodimage.images-bn.com/pimages/9780307408853_p0_v2_s550x406.jpg')
    book81.category.set([parent2, category12])

    book82 = Book.objects.create(author=author42,
                                 title='Billie Eilish',
                                 price='27.99',
                                 first_published=2021,
                                 description='Billie Eilish is a phenomenon. With distinctive visual flare and darkly poignant lyrics that are unparalleled among music icons of the 21st century, Billie is a musician who stands out from the crowd. Between her record-shattering award-winning music and her uncompromising and unapologetic attitude, it\'s no surprise that her fanbase continues to grow by millions month after month. She is that rare combination of wildly popular and highly respected for her prodigious talent, a once in a generation superstar.',
                                 url='https://prodimage.images-bn.com/pimages/9781538720479_p0_v8_s550x406.jpg')
    book82.category.set([parent2, category12])

    #Biography category
    book82 = Book.objects.create(author=author43,
                                 title='Between the World and Me',
                                 price='20.99',
                                 first_published=2015,
                                 description='Between the World and Me is Ta-Nehisi Coates’s attempt to answer these questions in a letter to his adolescent son. Coates shares with his son—and readers—the story of his awakening to the truth about his place in the world through a series of revelatory experiences, from Howard University to Civil War battlefields, from the South Side of Chicago to Paris, from his childhood home to the living rooms of mothers whose children’s lives were taken as American plunder.',
                                 url='https://prodimage.images-bn.com/pimages/9780812993547_p0_v5_s550x406.jpg')
    book82.category.set([parent2, category13])

    book83 = Book.objects.create(author=author44,
                                 title='A Promised Land',
                                 price='39.99',
                                 first_published=2020,
                                 description='Obama takes readers on a compelling journey from his earliest political aspirations to the pivotal Iowa caucus victory that demonstrated the power of grassroots activism to the watershed night of November 4, 2008, when he was elected 44th president of the United States, becoming the first African American to hold the nation’s highest office.',
                                 url='https://prodimage.images-bn.com/pimages/9781524763169_p0_v2_s550x406.jpg')
    book83.category.set([parent2, category13])

    book84 = Book.objects.create(author=author44,
                                 title='Dreams from My Father: A Story of Race and Inheritance',
                                 price='19.99',
                                 first_published=2004,
                                 description='In this lyrical, unsentimental, and compelling memoir, the son of a black African father and a white American mother searches for a workable meaning to his life as a black American. It begins in New York, where Barack Obama learns that his father—a figure he knows more as a myth than as a man—has been killed in a car accident. This sudden death inspires an emotional odyssey—first to a small town in Kansas, from which he retraces the migration of his mother’s family to Hawaii, and then to Kenya, where he meets the African side of his family, confronts the bitter truth of his father’s life, and at last reconciles his divided inheritance.',
                                 url='https://prodimage.images-bn.com/pimages/9781400082773_p0_v3_s550x406.jpg')
    book84.category.set([parent2, category13])

    book85 = Book.objects.create(author=author45,
                                 title='The Marathon Don\'t Stop: The Life and Times of Nipsey Hussle',
                                 price='25.99',
                                 first_published=2021,
                                 description='In the ten years since he first met Nipsey Hussle in the offices of Vibe, journalist Rob Kenner followed Hussle’s career, paying close attention to the music and business movement he was building in Los Angeles. Ten years later, they spoke again. To Kenner, it became clear that Hussle had been underestimated his entire life—not just for his artistry but also for his intellect and intentions.',
                                 url='https://prodimage.images-bn.com/pimages/9781982140298_p0_v3_s550x406.jpg')
    book85.category.set([parent2, category13])

    book86 = Book.objects.create(author=author46,
                                 title='Heart and Steel',
                                 price='30.99',
                                 first_published=2021,
                                 description='In HEART AND STEEL, Cowher will take readers on his journey from childhood to the undersized, mohawked, disco-dancing North Carolina State linebacker, to fighting for a spot as a "bubble player" with the Browns and Eagles, before injuries ended his playing career. ',
                                 url='https://prodimage.images-bn.com/pimages/9781982186005_p0_v1_s550x406.jpg')
    book86.category.set([parent2, category13])

    #Cookbook category
    book87 = Book.objects.create(author=author47,
                                 title='The Body Reset Diet: Power Your Metabolism, Blast Fat, and Shed Pounds in Just 15 Days',
                                 price='17.99',
                                 first_published=2014,
                                 description='In The Body Reset Diet, celebrity trainer and New York Times bestselling author Harley Pasternak offers you the ultimate plan for a thinner, healthier, happier life. This three-phase program focuses on the easiest, most effective way to slim down: blending. The 5-day jump-start includes delicious, expertly crafted smoothies (White Peach Ginger, Apple Pie, and Pina Colada, to name a few), dips, snacks, and soups that keep you satisfied while boosting your metabolism.',
                                 url='https://prodimage.images-bn.com/pimages/9781623362522_p0_v4_s550x406.jpg')
    book87.category.set([parent2, category14])

    book88 = Book.objects.create(author=author47,
                                 title='The Body Reset Diet Cookbook: 150 Recipes to Power Your Metabolism, Blast Fat, and Shed Pounds in Just 15 Days',
                                 price='20.99',
                                 first_published=2020,
                                 description='The Body Reset Diet Cookbook will keep your metabolism humming, so you’ll continue to blast through calories, shed pounds, and achieve your weight-loss goals.',
                                 url='https://prodimage.images-bn.com/pimages/9780593232538_p0_v1_s550x406.jpg')
    book88.category.set([parent2, category14])

    book89 = Book.objects.create(author=author48,
                                 title='Super Natural Simple: Whole-Food, Vegetarian Recipes for Real Life ',
                                 price='25.99',
                                 first_published=2021,
                                 description='When life gets busy, it often seems easier to order in or grab something on the go than to cook at home. But this is precisely when wholesome, nutrient-packed meals are needed the most. In Super Natural Simple, beloved blogger and New York Times bestselling author Heidi Swanson offers 120 smartly streamlined recipes—with minimal ingredients, timesaving tips, and creative flavor combinations—to make healthy home cooking completely doable.',
                                 url='https://prodimage.images-bn.com/pimages/9781984856883_p0_v2_s550x406.jpg')
    book89.category.set([parent2, category14])

    book90 = Book.objects.create(author=author48,
                                 title='Super Natural Every Day: Well-Loved Recipes from My Natural Foods Kitchen',
                                 price='26.99',
                                 first_published=2011,
                                 description='In Super Natural Every Day, Heidi helps us make nutritionally packed meals part of our daily repertoire by sharing a sumptuous collection of nearly 100 of her go-to recipes. These are the dishes that Heidi returns to again and again because they’re approachable, good for the body, and just plain delicious. This stylish cookbook is equal parts inspiration and instruction, showing us how to create a welcoming table filled with nourishing food for friends and family. ',
                                 url='https://prodimage.images-bn.com/pimages/9781580082778_p0_v1_s550x406.jpg')
    book90.category.set([parent2, category14])

    book91 = Book.objects.create(author=author49,
                                 title='Cook, Eat, Repeat: Ingredients, Recipes, and Stories',
                                 price='30.99',
                                 first_published=2021,
                                 description='Cook, Eat, Repeat is a delicious and delightful combination of recipes intertwined with narrative essays about food, all written in Nigella Lawson’s engaging and insightful prose. Whether asking “what is a recipe?” or declaring death to the “guilty pleasure,” Nigella brings her wisdom about food and life to the fore while sharing new recipes that readers will want to return to again and again.',
                                 url='https://prodimage.images-bn.com/pimages/9780063079540_p0_v5_s550x406.jpg')
    book91.category.set([parent2, category14])

    book92 = Book.objects.create(author=author50,
                                 title='Cook This Book: Techniques That Teach and Recipes to Repeat',
                                 price='18.99',
                                 first_published=2021,
                                 description='Molly breaks the essentials of cooking down to clear and uncomplicated recipes that deliver big flavor with little effort and a side of education, including dishes like Pastrami Roast Chicken with Schmaltzy Onions and Dill, Chorizo and Chickpea Carbonara, and of course, her signature Cae Sal. But this is not your average cookbook.',
                                 url='https://prodimage.images-bn.com/pimages/9780593138281_p0_v1_s550x406.jpg')
    book92.category.set([parent2, category14])

    #Home & Garden
    book93 = Book.objects.create(author=author51,
                                 title='A Beginner\'s Guide to Succulent Gardening: A Step-by-Step Guide to Growing Beautiful & Long-Lasting Succulents',
                                 price='15.99',
                                 first_published=2019,
                                 description='This book contains all sorts of helpful tips on what to look for when buying a plant, how to troubleshoot when your succulent shows signs of distress, how to trim the leaves and stems, and how to start new plants from cuttings. Clear diagrams and at-a-glance fact sheets for each variety, as well as inspirational photos of attractively and happily-housed succulents, fill the pages of this book. ',
                                 url='https://prodimage.images-bn.com/pimages/9780804851190_p0_v2_s550x406.jpg')
    book93.category.set([parent2, category15])

    book94 = Book.objects.create(author=author52,
                                 title='The Home Edit Life',
                                 price='28.99',
                                 first_published=2020,
                                 description='thors Clea Shearer and Joanna Teplin excel at organization, but they also enjoy doing it with style. Whether it\'s adding labels to containers or sensibly (and artfully) arranging items in the fridge, anyone can feel great because, in the end, organization is the path to getting rid of stuff. Now, in their new book, they will challenge you to apply the same principles to other aspects of your life so you can take control without the stress. It\'s a book that works well as a gift and certainly when the new year comes around—a perfect book to start the year right.',
                                 url='https://prodimage.images-bn.com/pimages/9780593138304_p0_v2_s550x406.jpg')
    book94.category.set([parent2, category15])

    book95 = Book.objects.create(author=author52,
                                 title='The Home Edit: A Guide to Organizing and Realizing Your House Goals',
                                 price='25.99',
                                 first_published=2019,
                                 description='Believe this: every single space in your house has the potential to function efficiently and look great. The mishmash of summer and winter clothes in the closet? Yep. Even the dreaded junk drawer? Consider it done. And the best news: it’s not hard to do—in fact, it’s a lot of fun. ',
                                 url='https://prodimage.images-bn.com/pimages/9780525572640_p0_v3_s550x406.jpg')
    book95.category.set([parent2, category15])

    book96 = Book.objects.create(author=author52,
                                 title='The Home Edit Workbook: Prompts, Activities, and Gold Stars to Help You Contain the Chaos',
                                 price='17.99',
                                 first_published=2021,
                                 description='lea Shearer and Joanna Teplin are back with a fun, practical workbook to jumpstart your home organization. Here are 52 challenges for every room—from clearing out a junk drawer to measuring your cabinet for storage bins to arranging the apps on your phone by color. ',
                                 url='https://prodimage.images-bn.com/pimages/9780593139820_p0_v13_s550x406.jpg')
    book96.category.set([parent2, category15])

    book97 = Book.objects.create(author=author53,
                                 title='Floret Farm\'s Cut Flower Garden: Grow, Harvest, and Arrange Stunning Seasonal Blooms',
                                 price='30.99',
                                 first_published=2017,
                                 description='A stunning flower book: This beautiful gardening book and guide to growing, harvesting, and arranging gorgeous blooms year round provides readers with vital tools to nurture a stunning flower garden and use their blossoms and cut flowers to create show stopping arrangements. It makes a beautiful gift for any occasion, for friends, loved ones and gardening lovers alike!',
                                 url='https://prodimage.images-bn.com/pimages/9781452145761_p0_v1_s550x406.jpg')
    book97.category.set([parent2, category15])

    # book98 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book98.category.set([parent2, category1])
    #
    # book99 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book99.category.set([parent2, category1])
    #
    # book100 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book100.category.set([parent2, category1])
    #
    # book101 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book101.category.set([parent2, category1])
    #
    # book102 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book102.category.set([parent2, category1])
    #
    # book103 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book103.category.set([parent2, category1])
    #
    # book104 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book104.category.set([parent2, category1])
    #
    # book105 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book105.category.set([parent2, category1])
    #
    # boo106 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book106.category.set([parent2, category1])
    #
    # book107 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book107.category.set([parent2, category1])
    #
    # book108 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book108.category.set([parent2, category1])
    #
    # book109 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book109.category.set([parent2, category1])
    #
    # book110 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book110.category.set([parent2, category1])
    #
    #
    # book111 = Book.objects.create(author=author,
    #                              title='',
    #                              price='',
    #                              first_published=,
    #                              description='',
    #                              url='')
    # book111.category.set([parent2, category1])

class Migration(migrations.Migration):
    dependencies = [
        ('store', '0022_auto_20210505_2347'),
    ]

    operations = [
        migrations.RunPython(populate_database)
    ]
