# Generated by Django 3.1.6 on 2021-05-05 20:51

from django.db import migrations

from store.models import Category, Author, Book


def populate_database(apps, schema_editor):
    Category.objects.all().delete()
    Author.objects.all().delete()

    # Categories
    parent1 = Category.objects.create(name='Fiction', is_child=False, parent_category=None)
    category1 = Category.objects.create(name='Science & Fiction', is_child=True, parent_category=parent1)
    category2 = Category.objects.create(name='Action & adventure', is_child=True, parent_category=parent1)
    category3 = Category.objects.create(name='Comic book', is_child=True, parent_category=parent1)
    category4 = Category.objects.create(name='Crime', is_child=True, parent_category=parent1)
    category5 = Category.objects.create(name='Fantasy', is_child=True, parent_category=parent1)
    category6 = Category.objects.create(name='Horror', is_child=True, parent_category=parent1)
    category7 = Category.objects.create(name='Thriller', is_child=True, parent_category=parent1)
    category8 = Category.objects.create(name='Satire', is_child=True, parent_category=parent1)
    category9 = Category.objects.create(name='Young adult', is_child=True, parent_category=parent1)
    category10 = Category.objects.create(name='Romance', is_child=True, parent_category=parent1)
    category11 = Category.objects.create(name='Mystery', is_child=True, parent_category=parent1)
    category25 = Category.objects.create(name='War', is_child=True, parent_category=parent1)

    parent2 = Category.objects.create(name='Nonfiction', is_child=False, parent_category=None)
    category12 = Category.objects.create(name='Art/architecture', is_child=True, parent_category=parent2)
    category13 = Category.objects.create(name='Biography', is_child=True, parent_category=parent2)
    category14 = Category.objects.create(name='Cookbook', is_child=True, parent_category=parent2)
    category15 = Category.objects.create(name='Dictionary', is_child=True, parent_category=parent2)
    category16 = Category.objects.create(name='Encyclopedia', is_child=True, parent_category=parent2)
    category17 = Category.objects.create(name='Guide', is_child=True, parent_category=parent2)
    category18 = Category.objects.create(name='Health/fitness', is_child=True, parent_category=parent2)
    category19 = Category.objects.create(name='History', is_child=True, parent_category=parent2)
    category20 = Category.objects.create(name='Humor', is_child=True, parent_category=parent2)
    category21 = Category.objects.create(name='Journal', is_child=True, parent_category=parent2)
    category22 = Category.objects.create(name='Math', is_child=True, parent_category=parent2)
    category23 = Category.objects.create(name='Philosophy', is_child=True, parent_category=parent2)
    category24 = Category.objects.create(name='Science', is_child=True, parent_category=parent2)

    # Authors
    author1 = Author.objects.create(name='George R.R.', surname='Martin')
    author2 = Author.objects.create(name='C.S.', surname='Lewis')
    author3 = Author.objects.create(name='Jack', surname='Higgins')
    author4 = Author.objects.create(name='Dan', surname='Brown')
    author5 = Author.objects.create(name='Louise', surname='Hay')
    author6 = Author.objects.create(name='Agatha', surname='Christie')
    author7 = Author.objects.create(name='Stephen', surname='Hawking')

    # Books
    book1 = Book.objects.create(author=author1,
                                title='A Game of Thrones',
                                price='60',
                                first_published=2003,
                                description='This first book in the A Song of Ice and Fire series boasts intricate plots, characters threatened with death, and a world chock-full of wizards, knights, ladies, and bastards. The book follows three storylines: one set in the seven kingdoms, another on the wall, and the third across the sea.',
                                url='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwritingcenter.mcdaniel.edu%2Fwp-content%2Fuploads%2F2012%2F11%2Fa-game-of-thrones-book-1-of-a-song-of-ice-and-fire.jpg&f=1&nofb=1')
    book1.category.set([parent1, category5])

    book2 = Book.objects.create(author=author2,
                                title='A Game of Thrones',
                                price='30',
                                first_published=1960,
                                description='Master storyteller C.S. Lewis introduces us to the magical world of Narnia as Lucy, Edmund, Peter, and Susan enter it through a wardrobe in their uncle’s house. Edmund encounters the White Witch, who convinces him to betray his siblings, but the Great Lion Aslan comes to their rescue—and that of the whole world of Narnia.',
                                url='https://duckduckgo.com/i/70cc686b.jpg')
    book2.category.set([parent1, category5])

    book3 = Book.objects.create(author=author3,
                                title='The Eagle Has Landed',
                                price='33.99',
                                first_published=2010,
                                description='Meanwhile, in a quiet seaside village, a beautiful widow and an IRA assassin have already laid the groundwork for what will be the most treacherous plot of the war. It begins on November 6, 1943, when Berlin receivs the fateful message...',
                                url='https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/TheEagleHasLanded.jpg/220px-TheEagleHasLanded.jpg')
    book3.category.set([parent1, category25, category7])

    book4 = Book.objects.create(author=author4,
                                title='The Da Vinci Code',
                                price='61.99',
                                first_published=2018,
                                description='While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter. Even more startling, the late curator was involved in the Priory of Sion—a secret society whose members included Sir Isaac Newton, Victor Hugo, and Da Vinci—and he guarded a breathtaking historical secret. Unless Langdon and Neveu can decipher the labyrinthine puzzle—while avoiding the faceless adversary who shadows their every move—the explosive, ancient truth will be lost forever.',
                                url='https://images-na.ssl-images-amazon.com/images/I/41KuPr7kpZL._SX277_BO1,204,203,200_.jpg')
    book4.category.set([parent1, category11, category7])

    book5 = Book.objects.create(author=author5,
                                title='You Can Heal Your Life',
                                price='21.99',
                                first_published=1984,
                                description='Louise L. Hay, bestselling author, is an internationally known leader in the self-help field. Her key message is: "If we are willing to do the mental work, almost anything can be healed." The author has a great deal of experience and firsthand information to share about healing, including how she cured herself after being diagnosed with cancer.',
                                url='https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/You_Can_Heal_Your_Life.jpg/220px-You_Can_Heal_Your_Life.jpg')
    book5.category.set([parent2, category19])

    book6 = Book.objects.create(author=author6,
                                title='And Then There Were None',
                                price='41.39',
                                first_published=1939,
                                description='Ten . . . Ten strangers are lured to an isolated island mansion off the Devon coast by a mysterious "U. N. Owen. Nine . . . At dinner a recorded message accuses each of them in turn of having a guilty secret, and by the end of the night one of the guests is dead. Eight . . . Stranded by a violent storm, and haunted by a nursery rhyme counting down one by one . . . as one by one . . . they begin to die. Seven . . .Which among them is the killer and will any of them survive?',
                                url='https://upload.wikimedia.org/wikipedia/en/4/4a/And_Then_There_Were_None_First_Edition_Cover_1939.jpg')
    book6.category.set([parent1, category11])

    book7 = Book.objects.create(author=author7,
                                title='A Brief History of Time',
                                price='51.99',
                                first_published=1988,
                                description='A landmark volume in science writing by one of the great minds of our time, Stephen Hawking’s book explores such profound questions as: How did the universe begin—and what made its start possible? Does time always flow forward? Is the universe unending—or are there boundaries? Are there other dimensions in space? What will happen when it all ends? Told in language we all can understand, A Brief History of Time plunges into the exotic realms of black holes and quarks, of antimatter and “arrows of time,” of the big bang and a bigger God—where the possibilities are wondrous and unexpected. With exciting images and profound imagination, Stephen Hawking brings us closer to the ultimate secrets at the very heart of creation.',
                                url='https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/BriefHistoryTime.jpg/220px-BriefHistoryTime.jpg')
    book7.category.set([parent2, category24])


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0022_auto_20210505_2347'),
    ]

    operations = [
        migrations.RunPython(populate_database)
    ]
