# Generated by Django 3.1.6 on 2021-05-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210509_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='OrderContact',
        ),
    ]
