# Generated by Django 3.1.6 on 2021-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20210509_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontact',
            name='ap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontact',
            name='bl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontact',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontact',
            name='sc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
