# Generated by Django 3.1.6 on 2021-05-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20210509_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
