# Generated by Django 3.1.6 on 2021-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_order_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
